version: 3.1.0.{build}
branches:
  except:
    - release/*
    - docs
skip_commits:
  message: /(Create|Add).*\.(png|jpg|jpeg|bmp|gif|md)/
#init:
#- git config --global core.autocrlf input
skip_tags: true
os: Visual Studio 2015
configuration: release
platform: x86
clone_depth: 5
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  access_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
build_script:
- ps: nuget restore
- ps: copy-item -path packages -destination src -recurse
- msbuild "Gemini.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#- mkdir build
#- mkdir build\%configuration%
- echo "%appveyor_build_version%" > build\%configuration%\VersionInfo.dat
#- cp src\bin\%configuration%\Gemini.exe build\%configuration%\Gemini.exe
- 7z a src\bin\%configuration%\Gemini.zip src\bin\%configuration%\Gemini.exe
artifacts:
- path: src\bin\$(configuration)\Gemini.zip
  name: Gemini
before_deploy:
-
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Gemini v$(appveyor_build_version)
  description: Autocompiled build from Appveyor.
  auth_token:
    secure: kFaS3hFnbZuEAGLC9L5zYcom8fYp6vYmLTjoMJtvP5vffxrHSIZAT1ADp7BWxO7ii7lY0WhuX3+oN592hZbW5q823Jv3wU8ErCZFxAjAmWA=
  artifact: src\bin\$(configuration)\Gemini.zip
#on_success:
#  - git config credential.helper store
#  - echo "https://%access_token%:x-oauth-basic@github.com" > "%userprofile%\.git-credential
#  - git add -f build
#  - git commit -m "Add latest build from AppVeyor\n[skip ci]"
#  - git push --verbose origin release/%appveyor_repo_branch%
